name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: output
          path: output

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: osyra42
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark
            snake.gif
          svg_only: false

      - name: Verify Files Exist
        id: verify
        run: |
          echo "Checking generated files..."
          ls -la
          if [ ! -f "snake.svg" ]; then
            echo "::error::snake.svg was not generated!"
            exit 1
          fi
          echo "Files verified successfully"

      - name: Commit and Push
        working-directory: ./output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update snake: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin output
