name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs at minute 0 past every 12th hour

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg?palette=github-dark

      - name: Commit and push snake.svg to output branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { repo, owner } = context.repo;
            const message = 'Update snake animation';
            const branch = 'output';
            
            // Check if file exists
            if (!fs.existsSync('snake.svg')) {
              core.setFailed('snake.svg not found');
              return;
            }

            // Push directly to output branch
            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path: 'snake.svg',
              message,
              content: fs.readFileSync('snake.svg', { encoding: 'base64' }),
              branch
            });
