name: Update Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: osyra42  # Hardcoded your username here
          outputs: |
            snake.svg
            snake.gif
          palette: github-dark

      - name: Checkout Output Branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: output-files

      - name: Move Files
        run: |
          mkdir -p output-files
          mv snake.svg output-files/
          mv snake.gif output-files/

      - name: Commit & Push
        run: |
          cd output-files
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update snake animation - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
